config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  get "pass", to: "pages#pass", as: :pass

  get "refactor", to: "pages#refactor", as: :refactor

  get "do_refactor", to: "pages#do_refactor", as: :do_refactor

  get "write_code", to: "pages#write_code", as: :write_code

  get "write_test", to: "pages#write_test", as: :write_test

  get "new_feature", to: "pages#new_feature", as: :new_feature

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PairProgrammingBot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/do_refactor.html.erb
<h1>Refactor the code.</h1>

<button><%= link_to "Done", pass_path %></button>

app/views/pages/index.html.erb
<h1>Do you have a test for that?</h1>

<button><%= link_to "Yes", pass_path %></button>

<button><%= link_to "No", write_test_path %></button>

app/views/pages/new_feature.html.erb
<h1>Select a new feature to implement.</h1>

<button><%= link_to "Continue", root_path %></button>

app/views/pages/pass.html.erb
<h1>Does the test pass?</h1>

<button><%= link_to "Yes", refactor_path %></button>

<button><%= link_to "No", write_code_path  %></button>

app/views/pages/refactor.html.erb
<h1>Need to refactor?</h1>

<button><%= link_to "Yes", do_refactor_path %></button>

<button><%= link_to "No", new_feature_path %></button>

app/views/pages/write_code.html.erb
<h1>Write just enough code for the test to pass</h1>

<button><%= link_to "Done", pass_path %></button>

app/views/pages/write_test.html.erb
<h1>Write a test.</h1>

<button><%= link_to "Done", pass_path %></button>